# Generated by Django 6.0.3 on 2026-05-08 23:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneurprofile',
            name='qr_code_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='hopitalprofile',
            name='licence_doc',
            field=models.FileField(blank=True, null=True, upload_to='licences/'),
        ),
        migrations.AddField(
            model_name='hopitalprofile',
            name='signature_electronique',
            field=models.TextField(blank=True, help_text='Signature au format Base64', null=True),
        ),
    ]
