# Generated by Django 6.0.3 on 2026-05-08 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donneurprofile_qr_code_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneurprofile',
            name='qr_code_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
