# Generated by Django 6.0.3 on 2026-05-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_donneurprofile_qr_code_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopitalprofile',
            name='signature_electronique',
        ),
    ]
