# Generated by Django 5.2.13 on 2026-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_hopitalprofile_signature_electronique'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopitalprofile',
            name='latitude',
            field=models.FloatField(default=35.8284),
        ),
        migrations.AddField(
            model_name='hopitalprofile',
            name='longitude',
            field=models.FloatField(default=10.635),
        ),
    ]
