# Generated by Django 5.2.13 on 2026-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hopitalprofile_latitude_hopitalprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopitalprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hopitalprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
