# Generated by Django 5.2.11 on 2026-05-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hopitaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateField()),
                ('quantite', models.PositiveIntegerField(help_text='Quantité en ml (ex: 450)')),
                ('lieu', models.CharField(max_length=200)),
                ('observations', models.TextField(blank=True, null=True)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='accounts.donneurprofile')),
                ('hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons_recus', to='accounts.hopitalprofile')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date_don'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_horaire', models.CharField(help_text='Ex: 09:00 - 10:00', max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='hopitaux.campagnecollecte')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='accounts.donneurprofile')),
            ],
            options={
                'verbose_name': 'Inscription à une campagne',
                'unique_together': {('donneur', 'campagne')},
            },
        ),
        migrations.CreateModel(
            name='ReponseAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='hopitaux.demandesang')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_appels', to='accounts.donneurprofile')),
            ],
            options={
                'verbose_name': 'Réponse à un appel',
                'verbose_name_plural': 'Réponses aux appels',
                'ordering': ['-date_reponse'],
                'unique_together': {('donneur', 'demande')},
            },
        ),
    ]
