# Generated by Django 5.2.11 on 2026-04-20 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_validated_alter_user_role_and_more'),
        ('donneurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='accounts.donneurprofile'),
        ),
        migrations.AddField(
            model_name='don',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hopitalprofile'),
        ),
        migrations.CreateModel(
            name='ReponseAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande_id', models.IntegerField()),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='en attente', max_length=50)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donneurprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DonneurProfile',
        ),
    ]
