# Generated by Django 6.0.3 on 2026-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donneurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='signature_donneur',
            field=models.TextField(blank=True, help_text='Signature Base64 du donneur lors du don', null=True),
        ),
    ]
