# Generated by Django 5.2.11 on 2026-04-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_validated_alter_user_role_and_more'),
        ('donneurs', '0002_alter_don_donneur_don_hopital_reponseappel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='don',
            options={'ordering': ['-date_don'], 'verbose_name': 'Don', 'verbose_name_plural': 'Dons'},
        ),
        migrations.AlterModelOptions(
            name='reponseappel',
            options={'ordering': ['-date_reponse'], 'verbose_name': 'Réponse à un appel', 'verbose_name_plural': 'Réponses aux appels'},
        ),
        migrations.AlterField(
            model_name='don',
            name='date_don',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='don',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons_recus', to='accounts.hopitalprofile'),
        ),
        migrations.AlterField(
            model_name='don',
            name='quantite',
            field=models.PositiveIntegerField(help_text='Quantité en ml (ex: 450)'),
        ),
        migrations.AlterField(
            model_name='reponseappel',
            name='demande_id',
            field=models.IntegerField(verbose_name='ID de la demande urgente'),
        ),
        migrations.AlterField(
            model_name='reponseappel',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_appels', to='accounts.donneurprofile'),
        ),
        migrations.AlterField(
            model_name='reponseappel',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reponseappel',
            unique_together={('donneur', 'demande_id')},
        ),
    ]
