# Generated by Django 5.2.11 on 2026-05-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_hopitalprofile_signature_electronique'),
        ('donneurs', '0002_don_signature_donneur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.donneurprofile')),
            ],
            options={
                'verbose_name': 'Conversation chatbot',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MessageChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=10)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='donneurs.conversationchatbot')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
    ]
