# Generated by Django 5.2.11 on 2026-05-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_hopitalprofile_latitude_and_more'),
        ('donneurs', '0003_conversationchatbot_messagechatbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneurBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('premier_don', 'Premier Pas'), ('donneur_regulier', 'Donneur Régulier'), ('heros_sang', 'Héros du Sang'), ('repondeur_urgent', 'Répondeur Urgent'), ('fidele', 'Donneur Fidèle'), ('sauveur_vies', 'Sauveur de Vies')], max_length=50)),
                ('date_obtention', models.DateTimeField()),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.donneurprofile')),
            ],
            options={
                'verbose_name': 'Badge donneur',
                'ordering': ['date_obtention'],
                'unique_together': {('donneur', 'code')},
            },
        ),
    ]
