# Generated by Django 5.2.11 on 2026-05-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=200)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('groupes_cibles', models.CharField(default='Tous', help_text='Ex: A+, O-, Tous', max_length=200)),
                ('capacite_totale', models.PositiveIntegerField(default=50)),
                ('nb_creneaux', models.PositiveIntegerField(default=5, verbose_name='Nombre de créneaux horaires')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='accounts.hopitalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('quantite_necessaire', models.PositiveIntegerField(verbose_name='Nombre de poches')),
                ('delai', models.PositiveIntegerField(default=24, verbose_name='Délai (heures)')),
                ('description', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('cloturee', 'Clôturée')], default='active', max_length=20)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='accounts.hopitalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StockSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('quantite_poches', models.PositiveIntegerField(default=0)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='accounts.hopitalprofile')),
            ],
            options={
                'unique_together': {('hopital', 'groupe_sanguin')},
            },
        ),
    ]
