# Generated by Django 6.0.3 on 2026-04-25 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_validated_alter_user_role_and_more'),
        ('hopitaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandesang',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='accounts.hopitalprofile'),
        ),
        migrations.AlterField(
            model_name='campagnecollecte',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='accounts.hopitalprofile'),
        ),
        migrations.AlterField(
            model_name='demandesang',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demandesang',
            name='quantite_necessaire',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='HopitalProfile',
        ),
    ]
