# Generated by Django 5.2.11 on 2026-04-26 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_validated_alter_user_role_and_more'),
        ('hopitaux', '0002_alter_campagnecollecte_hopital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('quantite_poches', models.PositiveIntegerField(default=0)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='accounts.hopitalprofile')),
            ],
            options={
                'unique_together': {('hopital', 'groupe_sanguin')},
            },
        ),
    ]
